# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d62eb0b37a926f25e3eee9fd6e8b7a1222d9f4f039b615507079d8488ec633e4bec7bc574d547573fe78ea82eb5abd45782623b594ca988cc6be2cba303f5e

test:
  secret_key_base: e9628bbf541de2dc05e80e4ccb00673afb977a566add93ec726b86cfacf671c2b54b9159b4da346f4f9de2072421d9e1589e66dcf034e4772e9128b388c57eb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
